version: '3.4'

services: 
  mosquitto: 
    image: eclipse-mosquitto:2 
    ports:
      - 1883:1883 
    volumes:
      - ./mosquitto/mosquitto.conf:/mosquitto/config/mosquitto.conf 
      - mosquitto_data:/mosquitto/data 
      - mosquitto_log:/mosquitto/log 

  telegraf: 
    image: telegraf 
    volumes:
      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf 
    depends_on: 
      - influxdb

  influxdb: 
    image: influxdb:1.8 
    ports:
      - 8086:8086 
    volumes:
      - influxdb_data:/var/lib/influxdb 
    environment:
      - INFLUXDB_DB=iesceliabd 
      - INFLUXDB_ADMIN_USER=root 
      - INFLUXDB_ADMIN_PASSWORD=root 
      - INFLUXDB_HTTP_AUTH_ENABLED=true 

  grafana: 
    image: grafana/grafana:7.4.0 
    ports:
      - 3000:3000 
    volumes:
      - grafana_data:/var/lib/grafana 
      - ./grafana-provisioning/:/etc/grafana/provisioning 
    depends_on: 
      - influxdb

volumes:
  mosquitto_data:
  mosquitto_log:
  influxdb_data:
  grafana_data:    
